### ISSUE TITLE
YouTube Bar

### ISSUE THREAD

**Issue by cezaryn13** [azizLIGHT/youtube-show-hide-top-bar#1]
YouTube Bar, no longer comes back is only hidden, I think it was some YouTube update, it was working 1 Week ago, I waited to see if it came back, but it does not work again.

**Comment by azizLIGHT** [comment]
I think I fixed it. If you have the script installed from here as raw, your script manager should see the 1.0.1 version and recognize there's an update. If not just click the script and click Raw button and update it now

Let me know if it works OK

**Comment by cezaryn13** [comment]
Working perfectly, thanks
